version: "3"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "ContosoRegistry.azurecr.io/db-dev-small"
        ports: 
            - "1433:1433"